on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - run: sudo apt-get install --no-install-recommends -y moby-buildx
      #- name: Cache docker buildkit
      #  uses: actions/cache@v1
      #  with:
      #    path: ~/.docker-cache
      #    key: build-dqd-${{ github.ref }}
      - env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: docker buildx build -t soluto/dqd --cache-from=docker.pkg.github.com/soluto/dqd/app:cache --cache-to=docker.pkg.github.com/soluto/dqd/app:cache .
      - name: test-azure
        working-directory: ./integration/tests
        run: ./naive-azure.sh
      - name: test-sqs
        working-directory: ./integration/tests
        run: ./naive-sqs.sh
      - name: azure-error-test
        working-directory: ./integration/tests
        run: ./error-azure.sh
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: soluto/dqd/app
          tag_with_sha: ${{ github.ref == 'refs/heads/master'}}
          tag_with_ref: ${{ github.ref != 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}