on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-azure
        working-directory: ./integration/tests
        run: ./naive-azure.sh
      - name: test-sqs
        working-directory: ./integration/tests
        run: ./naive-sqs.sh
      - name: azure-error-test
        working-directory: ./integration/tests
        run: ./error-azure.sh
