on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install latest buildx
        run: mkdir -p ~/.docker/cli-plugins && wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64 && chmod a+x  ~/.docker/cli-plugins/docker-buildx
      - name: Cache docker buildkit
        uses: actions/cache@v1
        with:
          path: ~/.docker-cache
          key: build-dqd-${{ github.ref }}
      - env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
        working-directory: ./integration/docker
        run: docker buildx bake -f ./docker-compose.base.yaml -f ./docker-compose.worker.yaml -f ./docker-compose.producer.yaml --load --set *.cache-from=type=local,src=./docker-cache  *.cache-to=type=local,dest=./docker-cache 
      - name: test-azure
        working-directory: ./integration/tests
        run: ./naive-azure.sh
      - name: test-sqs
        working-directory: ./integration/tests
        run: ./naive-sqs.sh
      - name: azure-error-test
        working-directory: ./integration/tests
        run: ./error-azure.sh
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: soluto/dqd/app
          tag_with_sha: ${{ github.ref == 'refs/heads/master'}}
          tag_with_ref: ${{ github.ref != 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}